# Generated by Django 5.2.3 on 2025-06-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_Token',
            fields=[
                ('tokens_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100)),
                ('expired_at', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
    ]
